baseURL = "https://file.tirinfo.com"
languageCode = "id-id"
title = "tirinfo.com"
MetaDataFormat = "yaml"
themesDir = "themes"
theme = "web"
DefaultContentLanguage = "en"
disableHugoGeneratorInject = "true"

[params]
  # Site Author
  name = "tirinfo.com"
  author = "tirinfo.com"
  description = "berbagi ilmu pengetahuaan"
  subtitle = "berbagi ilmu pengetahuaan"
  favicon = ""
  logo = ""

[languages]
  [languages.en]
    languageName = "Indonesia"
    languageCode = "id-id"

# Biodata Author
[author]
    name = "tirinfo.com"
    homepage = "https://tirinfo.com"
    image = ""

[taxonomies]
    tag = "tags"

[permalinks]
    post = "/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "Always"
  filename = "sitemap.xml"
  priority = 1